spring:
    profiles:
        include:
          - apollo #子配置文件名必须为application-xxx.yml
          - dbstorage #仓储库
          - rocketmq #mq配置文件
          - mongo #mongo配置文件
          - redis #redis配置文件
          - externalapi #外部接口配置文件
    mvc:   
        view: 
            prefix: /WEB-INF/views/ #返回的前缀 
            suffix: .jsp #返回的后缀
    jackson: 
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
        serialization: 
           write-dates-as-timestamps: false

server:
  port: 9030
  servlet:
    context-path: /

mybatis:
  configLocation: classpath:mybatis-config.xml
  type-aliases-package: com.topideal.entity
  mapper-locations: classpath:ibatis/**/*.xml