server:
  port: 9100
  servlet:
    context-path: /
     
mybatis:
    configLocation: classpath:mybatis-config.xml
    type-aliases-package: com.topideal.entity
    mapper-locations: classpath:ibatis/**/*.xml
    
spring:
  application:
    name: derp-api
  profiles:
    include:
    - apollo #子配置文件名必须为application-xxx.yml
    - dbsystem #主服务数据库
    - rocketmq #mq
    - mongo #mongo
    - crawler #爬虫配置文件    
    - externalapi #外部接口配置文件 
    - eurekaclient #eureka配置文件
  mvc:   
    view: 
      prefix: / #返回的前缀 
      suffix: .jsp #返回的后缀
  jackson: 
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization: 
      write-dates-as-timestamps: false

            
            
            
            
            

        
            
            
