eureka:
  instance:
    metadataMap:
      zone: derp #服务注册分区
    #将自己的ip注册到Eureka Server上,默认为false表示注册微服务所在操作系统的hostname到Eureka Server
    prefer-ip-address: true
    #客户端向服务端发送心跳的时间间隔，单位为秒默认30
    lease-renewal-interval-in-seconds: ${eureka.client.lease-renewal-interval-in-seconds}
    #服务端收到最后一次心跳之后等待的时间上限，单位为秒，默认90
    lease-expiration-duration-in-seconds: ${eureka.client.lease-expiration-duration-in-seconds}
  client:
    serviceUrl:
      defaultZone: ${eureka.serviceUrl-defaultZone}
    registry-fetch-interval-seconds: ${eureka.client.registry-fetch-interval-seconds} #从eureka服务器获取注册表信息的时间间隔 单位秒，默认30