#令牌有效时长
token:
  timeout: 12600 #单位 秒 3600=1小时 12600=3.5小时
shiro:
  sesiontimeout: 12600000 #主系统shiro中  session 有效时间   单位毫秒 3600000=1小时 12600000=3.5小时

spring:
  redis:
    database: 0
    host: ${redis.host}
    port: ${redis.port}
    password: ${redis.password}
    timeout: 10000  # 连接超时时间（毫秒）
    pool:
      max-active: -1  # 连接池最大连接数（使用负值表示没有限制）
      max-wait: 10000 # 连接池最大阻塞等待时间（使用负值表示没有限制）毫秒
      max-idle: 300  # 连接池中的最大空闲连接
      min-idle: 20  # 连接池中的最小空闲连接

#web子服务IP
orderwebhost: ${webhost.order} #order web子服务ip
storagewebhost:  ${webhost.storage} #仓储web子服务ip
inventorywebhost: ${webhost.inventory} #库存web子服务ip
reportwebhost:  ${webhost.report} #报表web子服务ip http://127.0.0.1:9050
frontwebhost:  ${webhost.front} #前端服务ip http://10.10.102.208:89

#是否开启swagger
swaggerenable: ${swaggerenable}
